services:
  - type: web
    name: telegram-egg-bot
    env: python
    buildCommand: ""
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: DATABASE_URL
        sync: false
